### PR TITLE
Set Up Config Options for Project

### PR DESCRIPTION
**Pull request by WormJim**

### CODE REVIEW

**Comment by omenwolf** [comment]
@WormJim, I reviewed PR #1, and just needs the following
- getting started aspect on `README.md` (ex. "run `npm run build-frontend-dev`"... etc.)
- technology stack & general overview

Here's what I'm currently seeing
`npm run build-frontend-dev` cmd is rendering "hello world"

Screen Shot 2019-09-05 at 4 02 11 PM

**Review by badwolfbit — CHANGES_REQUESTED** [review]
- add "Getting Started" on `README.md`
- add technology stack info / general descriptor of the project on `README.md`

**Review by badwolfbit — CHANGES_REQUESTED** [review]
look at previous comment

**Comment by WormJim** [comment]
@omenwolf 

I've updated a couple things. 

The README is updated but there clearly needs more detail. I think opening a ticket to get this done would make more sense.  You and I can talk about what tech we want to add.  This PR#1 is mainly focused on setting up a basic environment. Either way, you'll find the README gives you the scripts to run.

You can test out the pro by running `frontend-pro` and then running `server-dev`.  Just add a test script to the `src/index.ts` file. The reason it wasn't working before is because there wasn't a static path in the server. I added that.

**Comment by WormJim** [comment]
@omenwolf 

You should also pull down the latest branch to ensure you are getting the content.

**Comment by omenwolf** [comment]
@WormJim this looks great! I added a new PR (#3) to have some changes to the README.md file

**Pull request merged**
